server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway

zuul:
  routes:
    authentication-service:
      url: http://localhost:8083
      path: /authentication-service/**
      serviceId: authentication-service
      sensitiveHeaders: Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: 'routes'