spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authentication
  application:
    name: authentication-service

security:
  jwt:
    token:
      secretKey: abcdef123456xy??a??AAAAA?adacvcbcbcbcbcbc
      expirationInDays: 7
      prefix: Bearer
      header: authorization

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true