spring:
  application:
    name: discovery-service
server:
  port:
    8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    maxThreadsForPeerReplication: 0